In [1]:
import numpy as np

# Import the needed libraries

**72. How to swap two rows of an array?** 

In [16]:
a = np.array([[1,2,3],[6,5,4],[9,8,7]])
print(f' \noriginal array -> {a}')

a[[2,0]] = a[[0,2]]
print(f' \narray with 2 rows swap -> {a}')



 
original array -> [[1 2 3]
 [6 5 4]
 [9 8 7]]
 
array with 2 rows swap -> [[9 8 7]
 [6 5 4]
 [1 2 3]]


**75. How to compute averages using a sliding window over an array?**

In [45]:
def moving_average(a, n) :
    test = np.cumsum(a, dtype=float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n

moving_average(np.arange(1,1000,10),10)

array([ 46.,  56.,  66.,  76.,  86.,  96., 106., 116., 126., 136., 146.,
       156., 166., 176., 186., 196., 206., 216., 226., 236., 246., 256.,
       266., 276., 286., 296., 306., 316., 326., 336., 346., 356., 366.,
       376., 386., 396., 406., 416., 426., 436., 446., 456., 466., 476.,
       486., 496., 506., 516., 526., 536., 546., 556., 566., 576., 586.,
       596., 606., 616., 626., 636., 646., 656., 666., 676., 686., 696.,
       706., 716., 726., 736., 746., 756., 766., 776., 786., 796., 806.,
       816., 826., 836., 846., 856., 866., 876., 886., 896., 906., 916.,
       926., 936., 946.])

In [25]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : integer or real
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : integer or real, optional
    Spacing between values.  For any output `out`, this is the distance
    between t