In [ ]:
# Import the needed libraries

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [23]:
import random
import numpy as np

x = np.random.rand(10,10)
minimum = np.min(x)
maximum = np.max(x)
print(f' MATRIX 10x10 : \n\n   {x}')
print(f' minimum value is:  {minimum}')
print(f' maximum value is:  {maximum}')

 MATRIX 10x10 : 

   [[0.7082701  0.00231318 0.65300141 0.8521263  0.72761589 0.39915975
  0.81985353 0.04659593 0.95681483 0.76419797]
 [0.17026495 0.16446004 0.53503675 0.78969802 0.37633651 0.75808053
  0.97860635 0.10534641 0.78381837 0.66289145]
 [0.59792018 0.95477918 0.63100032 0.63929065 0.59228244 0.73654317
  0.93623577 0.36181462 0.35460272 0.8585374 ]
 [0.11063212 0.28714811 0.9388063  0.46020395 0.30729362 0.83736311
  0.39136691 0.5246268  0.09971433 0.93446999]
 [0.42906223 0.50223773 0.93052895 0.37408262 0.40502008 0.59406505
  0.78206074 0.33845599 0.76079427 0.80019536]
 [0.23129914 0.35929783 0.43525227 0.36270814 0.31602476 0.62289426
  0.67713386 0.84453966 0.54366491 0.20421129]
 [0.83289896 0.89640105 0.98600982 0.67254659 0.53389718 0.42274474
  0.51585059 0.40514698 0.45620588 0.2012074 ]
 [0.26848615 0.23327712 0.53426045 0.36843041 0.31584597 0.630009
  0.06585474 0.48681719 0.38125954 0.87075151]
 [0.99411093 0.52192223 0.41161865 0.10759028 0.00955426 0.35

**15. Create a 2d array with 1 on the border and 0 inside**

In [55]:
x = np.ones((10,10))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
